#!/usr/bin/env python3
"""Generate src/assets/scene_art.h: palette-indexed sprites for the scene
engine (src/scene.c). All art is original, drawn on the pixel grids below.

Usage: python3 tools/gen_sprite_art.py

Sprite maps hold palette indices (see P_* in src/scene.h); 0 = transparent.
Char map:
  '.' transparent   'c' P_CLOUD    'm' P_MOON     'f' P_DARK (foliage)
  't' P_BLD (trunk) 'w' P_WHITE    'k' P_DARK     'p' P_COLLAR
  'a' P_ACC         'g' P_GLOW     'b' P_BLD      '2' P_BLD2
"""
import os

CH = {
    '.': 0, 'c': 7, 'm': 11, 'f': 13, 't': 4, 'w': 12, 'k': 13,
    'p': 14, 'a': 15, 'g': 6, 'b': 4, '2': 5,
}

GRIDS = {}

def grid(name, rows):
    w = len(rows[0])
    for r in rows:
        assert len(r) == w, f"{name}: row width {len(r)} != {w}"
    GRIDS[name] = (w, rows)

# ---- clouds: lumpy, flat bottom. Two frames each for a living sky ----
grid("cloud_0a", [
    ".....ccc....ccc.....",
    "...cccccccccccccc...",
    "..cccccccccccccccc..",
    ".cccccccccccccccccc.",
    ".cccccccccccccccccc.",
    "..cccccccccccccccc..",
    "...cccccccccccccc...",
    "....cccccccccccc....",
])
grid("cloud_0b", [
    "....ccc.....ccc.....",
    "..ccccccccccccccc...",
    ".ccccccccccccccccc..",
    ".cccccccccccccccccc.",
    ".cccccccccccccccccc.",
    "..cccccccccccccccc..",
    "...cccccccccccccc...",
    "....cccccccccccc....",
])
grid("cloud_1a", [
    "....cccccc....",
    "..cccccccccc..",
    ".cccccccccccc.",
    ".cccccccccccc.",
    "..cccccccccc..",
    "...cccccccc...",
])
grid("cloud_1b", [
    "...cccccc.....",
    ".cccccccccc...",
    ".cccccccccccc.",
    ".cccccccccccc.",
    "..cccccccccc..",
    "...cccccccc...",
])
grid("cloud_2a", [
    "........cc..........",
    "..ccc..cccccc..ccc..",
    ".ccccccccccccccccccc",
    "cccccccccccccccccccc",
    ".ccccccccccccccccccc",
    "..ccccccccccccccccc.",
    "...cccccccccccccc...",
    "....cccccccccccc....",
])
grid("cloud_2b", [
    ".......ccc..........",
    ".ccc..ccccccc..ccc..",
    "cccccccccccccccccccc",
    "cccccccccccccccccccc",
    ".ccccccccccccccccccc",
    "..ccccccccccccccccc.",
    "...cccccccccccccc...",
    "....cccccccccccc....",
])

# ---- moon: crescent (carved disc, carve shows the sky through) ----
grid("moon", [
    ".....mm......",
    "...mmmmm.....",
    "..mmmmmm.....",
    ".mmmmmmm.....",
    ".mmmmmmmm....",
    ".mmmmmmmm....",
    ".mmmmmmmm....",
    ".mmmmmmm.....",
    "..mmmmmm.....",
    "...mmmmm.....",
    ".....mm......",
])

# ---- tree: round canopy + trunk ----
grid("tree", [
    "...f...",
    "..fff..",
    ".fffff.",
    "fffffff",
    "fffffff",
    ".fffff.",
    "..fff..",
    "...t...",
    "...t...",
    "...t...",
])

# ---- lightning bolt ----
grid("bolt", [
    "...w...",
    "..w....",
    "..ww...",
    ".ww....",
    ".wwww..",
    "....w..",
    "...w...",
    "...ww..",
    "..w....",
    "..ww...",
    ".w.....",
    ".w.....",
    ".wwww..",
    "....w..",
    "...w...",
    "...ww..",
    "..w....",
    "..ww...",
    ".w.....",
    ".w.....",
    "..w....",
    "..ww...",
    "...w...",
    "...ww..",
    "....w..",
    "....w..",
    ".....w.",
])

# ---- potted plant for the window sill (leaves + terracotta pot) ----
grid("plant", [
    ".....2.....",
    "....222....",
    "..2222222..",
    ".222222222.",
    "..2222222..",
    "...22222...",
    "..aaaaaaa..",
    "..aaaaaaa..",
    "...aaaaa...",
    "...aaaa....",
])

def emit():
    out = []
    out.append("/* Generated by tools/gen_sprite_art.py -- do not edit by hand.")
    out.append(" * Palette-indexed sprite maps for src/scene.c; 0 = transparent,")
    out.append(" * other values are P_* slots from src/scene.h. */")
    out.append("#ifndef CLOCK_SCENE_ART_H")
    out.append("#define CLOCK_SCENE_ART_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    for name, (w, rows) in GRIDS.items():
        out.append(f"#define ART_{name.upper()}_W {w}")
        out.append(f"#define ART_{name.upper()}_H {len(rows)}")
        out.append(f"static const uint8_t art_{name}[{w * len(rows)}] = {{")
        vals = []
        for r in rows:
            vals.extend(CH[ch] for ch in r)
        for i in range(0, len(vals), 20):
            out.append("    " + ", ".join(str(v) for v in vals[i:i + 20]) + ",")
        out.append("};")
        out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(root, "src", "assets", "scene_art.h"), "w") as f:
        f.write(emit())
    print(f"wrote src/assets/scene_art.h: {len(GRIDS)} sprites, "
          f"{sum(w * len(r) for w, r in GRIDS.values())} px total")
    for name, (w, rows) in GRIDS.items():
        print(f"  {name}: {w}x{len(rows)}")
