#!/usr/bin/env python3
"""Generate src/assets/mistral_logo.h and src/assets/weather_icons.h.

All art is original, drawn on the character grids below in the Mistral
palette (yellow #FFD800, amber #FFAF00, orange #FF8205, red-orange #FA500F,
red #E10500) plus supporting neutrals and a blue accent (#55B3FB, #B9DAFF).

Usage:
  python3 tools/gen_pixel_art.py            write the headers
  python3 tools/gen_pixel_art.py --preview  print the grids, write nothing
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "assets")

PAL = {
    "Y": 0xFFD800,  # yellow
    "A": 0xFFAF00,  # amber
    "O": 0xFF8205,  # orange
    "R": 0xFA500F,  # red-orange
    "D": 0xE10500,  # red
    "K": 0x2B1A12,  # dark outline (warm near-black)
    "W": 0xFFE9C9,  # cream
    "w": 0xF5EDE0,  # warm off-white (cloud highlight)
    "g": 0x8A7F6D,  # warm gray (cloud body / fog)
    "H": 0x6B5D4A,  # storm gray (visible on dark/light/mid panels)
    "B": 0x55B3FB,  # mistral blue (rain)
    "s": 0xEAF3FF,  # snow white
    "S": 0xB9DAFF,  # snow-flake light blue (visible on cream AND dark)
    "E": 0x1A0F08,  # eye
}



def rgb565(c):
    r, g, b = (c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)



def render(grid, w):
    px = []
    for y, row in enumerate(grid):
        assert len(row) == w, f"row {y} width {len(row)} != {w}: {row!r}"
        for x, ch in enumerate(row):
            if ch != ".":
                px.append((x, y, rgb565(PAL[ch])))
    return px



def emit_c(name, w, h, frames, header_comment):
    lines = [f"/* {header_comment}",
             " * Generated by tools/gen_pixel_art.py -- do not edit by hand.",
             " * Format: RGB565 (LVGL lv_image, byte-swapped on flush). */",
             "#pragma once", "#include <stdint.h>", ""]
    for fname, px in frames:
        lines.append(f"#define {name}_{fname}_W {w}")
        lines.append(f"#define {name}_{fname}_H {h}")
        lines.append(f"static const uint16_t {name}_{fname}[{w * h}] = {{")
        grid = [[0] * w for _ in range(h)]
        for x, y, c in px:
            grid[y][x] = c
        for y in range(h):
            lines.append("    " + ", ".join(f"0x{v:04X}" for v in grid[y]) + ",")
        lines.append("};")
        # RGB565A8 variant: LVGL layout = [h rows of w RGB565 pixels]
        # followed by [h rows of w alpha bytes]. 0x0000 pixels are
        # transparent so icons/logo blend over any theme background.
        lines.append(f"#define {name}_{fname}_A8_SIZE ({w * h * 2 + w * h})")
        lines.append(f"static const uint8_t {name}_{fname}_a8[{name}_{fname}_A8_SIZE] = {{")
        for y in range(h):
            # uint8_t array: each RGB565 pixel = 2 bytes, low byte first
            # (little-endian host order, same as LVGL lv_color16_t in memory)
            row = []
            for v in grid[y]:
                row.append(f"0x{v & 0xFF:02X}")
                row.append(f"0x{v >> 8:02X}")
            lines.append("    " + ", ".join(row) + ",")
        for y in range(h):
            lines.append("    " + ", ".join("0xFF" if grid[y][x] else "0x00"
                                             for x in range(w)) + ",")
        lines.append("};")
        lines.append("")
    with open(os.path.join(OUT, f"{name}.h"), "w") as f:
        f.write("\n".join(lines))
    print(f"wrote src/assets/{name}.h ({len(frames)} frame(s), {w}x{h})")


def preview(title, grid):
    print(f"--- {title} ---")
    print("\n".join("  " + r for r in grid))



# Mistral pixel-M logo (2025 mark, 7x5 cells, traced from the official SVG,
# see assets/mistral/MISTRAL_M_GRID.md)
M_GRID = [
    ".X...X.",
    ".XX.XX.",
    ".XXXXX.",
    ".X.X.X.",
    "XXX.XXX",
]
M_COLORS = ["Y", "A", "O", "R", "D"]



def emit_logo(scale=3):
    w, h = 7 * scale, 5 * scale
    px = []
    for row, (gridrow, color) in enumerate(zip(M_GRID, M_COLORS)):
        for col, ch in enumerate(gridrow):
            if ch == "X":
                c = rgb565(PAL[color])
                for dy in range(scale):
                    for dx in range(scale):
                        px.append((col * scale + dx, row * scale + dy, c))
    emit_c("mistral_logo", w, h, [("img", px)],
           f"Mistral AI pixel-M logo (official 2025 mark), 7x5 cells x{scale} px.")


# Weather icons, 16x16
SUN = [
    "................",
    ".......YY.......",
    ".......YY.......",
    "...YY..YY..YY...",
    "...YYYYYYYYYY...",
    "....YYYYYYYY....",
    "....YYYYYYYY....",
    ".YY.YYYYYYYY.YY.",
    ".YY.YYYYYYYY.YY.",
    "....YYYYYYYY....",
    "....YYYYYYYY....",
    "...YYYYYYYYYY...",
    "...YY..YY..YY...",
    ".......YY.......",
    ".......YY.......",
    "................",
]
MOON = [
    "................",
    ".....YY.........",
    "...YYYYY........",
    "..YYYYYYY.......",
    "..YYYYYY........",
    ".YYYYYY.........",
    ".YYYY...........",
    ".YYYY...........",
    ".YYYYYY.........",
    "..YYYYYY........",
    "..YYYYYYY.......",
    "...YYYYY........",
    ".....YY.........",
    "................",
    "................",
    "................",
]
# Cloud family: K outline + g body + w highlight. The body is warm gray
# rather than white, which would vanish on the light theme background. The
# dark outline keeps clouds crisp on cream; the gray body carries them on dark.
CLOUD = [
    "................",
    "................",
    ".....KKKK..KK...",
    "...KKwgggKKggK..",
    "..KwggggggggggK.",
    ".KggggggggggggK.",
    ".KggggggggggggK.",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
]
PARTLY = [
    "....Y...........",
    "...KKKK.........",
    "..KAAAAK........",
    "Y.KAAAAAAK.Y....",
    "..KAAAAAAK......",
    "..KAAAAK........",
    "...KKKK.........",
    "....Y...........",
    "......KKKK..KK..",
    "....KKwgggKKggK.",
    "...KwgggggggggK.",
    "..KggggggggggggK",
    "..KggggggggggggK",
    "...KKKKKKKKKKKK.",
    "................",
    "................",
]
RAIN = [
    "................",
    ".....KKKK..KK...",
    "...KKwgggKKggK..",
    "..KwggggggggggK.",
    ".KggggggggggggK.",
    ".KggggggggggggK.",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "....B...B...B...",
    "...B...B...B....",
    "....B...B...B...",
    "...B...B...B....",
    "................",
    "................",
    "................",
]
DRIZZLE = [
    "................",
    ".....KKKK..KK...",
    "...KKwgggKKggK..",
    "..KwggggggggggK.",
    ".KggggggggggggK.",
    ".KggggggggggggK.",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "................",
    "...B.....B......",
    "................",
    "......B.....B...",
    "................",
    "...B.....B......",
    "................",
]
SNOW = [
    "................",
    ".....KKKK..KK...",
    "...KKwgggKKggK..",
    "..KwggggggggggK.",
    ".KggggggggggggK.",
    ".KggggggggggggK.",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "..S.....S.....S.",
    ".SSS...SSS...SSS",
    "..S.....S.....S.",
    "................",
    "....S......S....",
    "................",
    "................",
]
STORM = [
    "................",
    ".....KKKK..KK...",
    "...KKHHHHKKHHK..",
    "..KHHHHHHHHHHHHK",
    ".KHHHHHHHHHHHHK.",
    ".KHHHHHHHHHHHHK.",
    "..KKKKKKKKKKKK..",
    "................",
    "......YYYY......",
    ".....YYYY.......",
    "....YYYYY.......",
    ".....YY.........",
    "....YYY.........",
    "...YYYY.........",
    "....YY..........",
    "................",
]
FOG = [
    "................",
    ".....KKKK..KK...",
    "...KKwgggKKggK..",
    "..KwggggggggggK.",
    ".KggggggggggggK.",
    ".KggggggggggggK.",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "..gggggggggg....",
    "....gggggggg....",
    "..gggggggggg....",
    "....gggggggg....",
    "................",
    "................",
    "................",
]


ICONS = {"sun": SUN, "moon": MOON, "cloud": CLOUD, "partly": PARTLY,
         "rain": RAIN, "drizzle": DRIZZLE, "snow": SNOW, "storm": STORM,
         "fog": FOG}


def main():
    if "--preview" in sys.argv:
        for name, g in ICONS.items():
            preview(name.upper(), g)
        preview("M (7x5)", M_GRID)
        return
    emit_logo()
    frames = []
    for name, grid in ICONS.items():
        assert len(grid) == 16, name
        frames.append((name, render(grid, 16)))
    emit_c("weather_icons", 16, 16, frames, "Pixel weather icons, 16x16 RGB565.")


if __name__ == "__main__":
    main()

