#!/usr/bin/env python3
"""Generate src/assets/clock_digits.h: the home-screen clock digits.

Chunky 5x7 pixel glyphs at scale 4 with a baked 2 px outline. Every tile is
a solid opaque plate in the outline colour carrying the glyph, so the digits
stay legible over any live scene. Five colour schemes: dark, light and mid
theme fills, plus red variants shown while the time is not synced.

Output format: uint16 RGB565 plane + RGB565A8 `_a8` array per sprite, and a
[scheme][glyph] pointer table (same layout as the gen_pixel_art.py assets).

Usage:
  python3 tools/gen_clock_digits.py                 write the header
  python3 tools/gen_clock_digits.py --preview PNG   also write a 4x preview
                                                    of every glyph x scheme
                                                    (needs Pillow)
"""
import argparse
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_H = os.path.join(ROOT, "src", "assets", "clock_digits.h")

S = 4      # pixel scale: 1 grid cell = 4 px
T = 2      # outline thickness in px

# 5x7 grids, 1 = glyph cell. Counters are >=3 cells wide so the 2px
# outline never closes them.
GRIDS = {
    "0": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["01110", "10001", "00001", "00110", "01000", "10000", "11111"],
    "3": ["01110", "10001", "00001", "00110", "00001", "10001", "01110"],
    "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    "5": ["11111", "10000", "11110", "00001", "00001", "10001", "01110"],
    "6": ["01110", "10000", "10000", "11110", "10001", "10001", "01110"],
    "7": ["11111", "00001", "00010", "00100", "01000", "01000", "01000"],
    "8": ["01110", "10001", "10001", "01110", "10001", "10001", "01110"],
    "9": ["01110", "10001", "10001", "01111", "00001", "00010", "01100"],
    "-": ["00000", "00000", "00000", "11111", "00000", "00000", "00000"],
    ":": ["..", "..", "##", "..", "..", "##", ".."],   # dots straddle centre
}
GLYPH_ORDER = list("0123456789") + [":", "-"]   # table index 0..11

# (scheme, fill RGB888, outline RGB888): the outline contrasts with the fill
# and separates the glyphs from any scene colour behind them.
SCHEMES = [
    ("dark",      0xF5EDE0, 0x1A120B),
    ("light",     0x2B2118, 0xFFFFFF),
    ("mid",       0xF2E7D3, 0x241A12),
    ("red_dark",  0xFA500F, 0x1A120B),   # unsynced, dark/mid theme
    ("red_light", 0xC93A0E, 0xFFFFFF),   # unsynced, light theme
]


def rgb565(c):
    return ((c >> 16 & 0xF8) << 8) | ((c >> 8 & 0xFC) << 3) | (c & 0xF8) >> 3


def render(grid, fill, outline):
    """Return (w, h, pixels) where pixels[y][x] is fill or outline.

    The canvas is the glyph scaled by S plus a T px margin on every side.
    Every non-glyph pixel (outline ring, counters, notches, margin) gets the
    outline colour, so each tile is a solid opaque plate and no scene pixel
    shows through the glyph; the gap between tiles still shows the scene.
    """
    gh, gw = len(grid), len(grid[0])
    w, h = gw * S + 2 * T, gh * S + 2 * T
    glyph = [[False] * w for _ in range(h)]
    for gy, row in enumerate(grid):
        for gx, c in enumerate(row):
            if c in ("1", "#"):
                for dy in range(S):
                    for dx in range(S):
                        glyph[gy * S + T + dy][gx * S + T + dx] = True
    px = [[fill if glyph[y][x] else outline for x in range(w)]
          for y in range(h)]
    return w, h, px


def preview(path):
    from PIL import Image
    pad, cell = 4, 4
    glyphs = GLYPH_ORDER
    row_h = 32 * cell + 2 * pad
    img = Image.new("RGB", (len(glyphs) * (24 * cell + pad) + pad,
                            len(SCHEMES) * row_h + pad), (96, 88, 80))
    for si, (sname, fill, outline) in enumerate(SCHEMES):
        for gi, g in enumerate(glyphs):
            w, h, px = render(GRIDS[g], rgb565(fill), rgb565(outline))
            for y in range(h):
                for x in range(w):
                    v = px[y][x]
                    rgb = ((v >> 11) * 255 // 31, (v >> 5 & 63) * 255 // 63,
                           (v & 31) * 255 // 31)
                    for dy in range(cell):
                        for dx in range(cell):
                            img.putpixel((pad + gi * (24 * cell + pad) + x * cell + dx,
                                          pad + si * row_h + y * cell + dy), rgb)
    img.save(path)
    print(f"wrote {path}")


def emit_c():
    L = ["/* Home-screen clock digits: 5x7 pixel glyphs, scale 4, baked 2px",
         " * outline, RGB565A8. Each tile is a solid opaque plate (outline",
         " * colour) carrying the glyph, so digits stay solid over any scene.",
         " * Generated by tools/gen_clock_digits.py.",
         " * Do not edit by hand. */",
         "#pragma once", "#include <stdint.h>", "",
         "typedef struct { const uint16_t *px; const uint8_t *a8;",
         "                 uint16_t w, h; } clock_dig_t;", "",
         "#define CLOCK_DIG_SCHEMES 5",
         "#define CLOCK_DIG_GLYPHS 12   /* '0'-'9', ':' , '-' */", ""]
    table = []
    for sname, fill, outline in SCHEMES:
        f565, o565 = rgb565(fill), rgb565(outline)
        for g in GLYPH_ORDER:
            w, h, px = render(GRIDS[g], f565, o565)
            stem = f"clock_digits_{sname}_{g.replace(':', 'colon').replace('-', 'dash')}"
            L.append(f"#define {stem}_W {w}")
            L.append(f"#define {stem}_H {h}")
            L.append(f"static const uint16_t {stem}[{w * h}] = {{")
            for y in range(h):
                L.append("    " + ", ".join(f"0x{v:04X}" for v in px[y]) + ",")
            L.append("};")
            L.append(f"#define {stem}_A8_SIZE ({w * h * 3})")
            L.append(f"static const uint8_t {stem}_a8[{stem}_A8_SIZE] = {{")
            for y in range(h):
                L.append("    " + ", ".join(
                    f"0x{v & 0xFF:02X}, 0x{v >> 8:02X}" for v in px[y]) + ",")
            for y in range(h):  # alpha plane: every pixel is opaque
                L.append("    " + ", ".join(["0xFF"] * w) + ",")
            L.append("};")
            L.append("")
            table.append((sname, g, stem, w, h))
    L.append("/* [scheme][glyph] -> sprite; glyph index: 0-9, 10=':', 11='-' */")
    L.append("static const clock_dig_t clock_digits[CLOCK_DIG_SCHEMES]"
             "[CLOCK_DIG_GLYPHS] = {")
    for sname, _fill, _outline in SCHEMES:
        rows = [t for t in table if t[0] == sname]
        cells = ", ".join(
            f"{{ {t[2]}, {t[2]}_a8, {t[3]}, {t[4]} }}" for t in rows)
        L.append(f"    {{ {cells} }},   /* {sname} */")
    L.append("};")
    L.append("")
    with open(OUT_H, "w") as f:
        f.write("\n".join(L))
    print(f"wrote src/assets/clock_digits.h ({len(table)} sprites)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--preview", metavar="PNG",
                    help="also write a preview image (needs Pillow)")
    args = ap.parse_args()
    emit_c()
    if args.preview:
        preview(args.preview)
