#ifndef CLOCK_SCENE_H
#define CLOCK_SCENE_H

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"

/* Live background scene engine for the home screen and screensaver.
 *
 * The scene is a half-resolution (160x86) 4-bpp palette-indexed buffer,
 * upscaled 2x2 in the display flush path: pixels in the LVGL framebuffer
 * that equal the theme background colour (the "key") are replaced with the
 * scene pixel. LVGL keeps rendering into a pure framebuffer, so anti-alias
 * blending and `fb dump` stay correct; the same substitution is applied on
 * the dump path so captures show exactly what the panel shows.
 *
 * Art: sky bands graded per theme x phase (dawn/day/sunset/night), a static
 * layer (city skyline / nature hills+river / window with sill + plant +
 * mini cat) and dynamic weather (clouds, rain, snow, fog, lightning,
 * sun, moon, stars). Palette-indexed sprites live in flash, generated by
 * tools/gen_sprite_art.py and tools/gen_chaton.py. */

#define SCENE_W 160
#define SCENE_H 86

/* Palette slots. Sprite maps use 0 = transparent, otherwise one of these. */
enum {
    P_SKY0 = 0, P_SKY1, P_SKY2, P_SKY3,   /* sky bands, top -> horizon */
    P_BLD,                                /* silhouette / hill / frame */
    P_BLD2,                               /* lit windows / far hill / sill edge */
    P_GLOW,                               /* sun, clock face, river sparkle */
    P_CLOUD, P_RAIN, P_SNOW, P_FOG,
    P_MOON, P_WHITE, P_DARK, P_COLLAR, P_ACC,
    P_COUNT
};

typedef enum {
    SCENE_LAYER_CITY = 0, SCENE_LAYER_NATURE, SCENE_LAYER_WINDOW,
    SCENE_LAYER_AUTO, SCENE_LAYER_COUNT
} scene_layer_t;

typedef enum {
    SCENE_PHASE_DAWN = 0, SCENE_PHASE_DAY, SCENE_PHASE_SUNSET,
    SCENE_PHASE_NIGHT
} scene_phase_t;

typedef enum {
    SCENE_SCR_HOME = 0,     /* scene composited under the LVGL chrome */
    SCENE_SCR_SAVER,        /* screensaver: scene + cat */
    SCENE_SCR_OTHER         /* settings / location picker: flat bg */
} scene_screen_t;

esp_err_t scene_init(void);                 /* NVS + palette + anim task */
void scene_register_commands(void);         /* `scene` command */

void scene_set_screen(scene_screen_t s);    /* which screen is visible */
scene_screen_t scene_screen(void);

/* Substitute key pixels in one LVGL framebuffer row with scene pixels.
 * src points at pixel x1 (RGB565 LE); dst receives x2-x1+1 pixels and
 * must not alias src. Runs in the flush path, so it must stay cheap and
 * must not take locks (the LVGL lock is already held by the caller). */
void scene_composite_row(int y, const uint8_t *src, uint8_t *dst,
                         int x1, int x2);

void scene_theme_changed(void);             /* regrade + full invalidation */

/* Pixel-op wrappers for scene_chaton.c (the statics stay private). */
void scene_sset(int x, int y, int v);
void scene_sfill(int x0, int y0, int x1, int y1, int v);
void scene_stamp(const uint8_t *map, int w, int h, int x, int y);
bool scene_bolt_active(void);               /* a lightning flash is showing */

#endif
