/* Screensaver character: the Mistral pixel cat.
 *
 * A 13x11 px reference cat (white, dark eyes and nose, red-orange collar,
 * yellow bell, upright tail), scaled 3x with a thin outline. Sprites
 * live in src/assets/chaton.h, generated by tools/gen_chaton.py; the face
 * (eyes, nose) is stamped separately so the cat can blink, look and sleep.
 *
 * Scenarios: LOAF (sitting: tail sway, blinks, glances, ear twitch), SLEEP
 * (^ ^ eyes, slow tail, rising "z z z"), CHASE (eyes follow a rolling yarn
 * ball), MCHASE (a bouncing pixel-M block), EAT (looks down at a croissant
 * that loses bites), CURL (lying down asleep at night). They rotate every
 * ~20 s; `saver scenario <name>` pins one. The cat reacts to
 * the real weather and time: umbrella in rain, scarf in snow or cold,
 * sunglasses in strong sun, a bow tie at work hours, wide eyes while
 * lightning flashes.
 *
 * The environment is truthful: sky, light and weather effects
 * come from the latest real Open-Meteo data and the real sunrise/sunset.
 * When the data is missing or older than 3 h (or the clock is not synced)
 * the saver shows a neutral indoor scene instead (a warm wall, a rug, a
 * little framed pixel-M poster and the cat) and never invents weather.
 *
 * Runs entirely inside scene.c's 100 ms paint tick under the LVGL lock;
 * owns no tasks and no heap. */
#include <string.h>
#include <math.h>

#include "scene.h"
#include "scene_chaton.h"
#include "chaton.h"
#include "time_mgr.h"
#include "weather_mgr.h"

#define GROUND_Y   70           /* scene rows [GROUND_Y, SCENE_H) are ground */
#define CAT_X      58           /* rest position of the sitting cat */
#define CAT_Y      43           /* feet (outline row) land on y = CAT_Y + 34 */
#define LIE_X      74           /* lying position, under the moon (x=122) */
#define LIE_Y      52
#define ROT_TICKS  200          /* auto scenario rotation period (20 s) */

typedef enum {
    SC_SLEEP = 0, SC_LOAF, SC_CHASE, SC_EAT, SC_MCHASE, SC_CURL, SC_COUNT
} scen_t;

static scen_t s_scen = SC_LOAF;
static int s_pin = -1;          /* -1 = auto rotate */
static uint32_t s_tick;
static uint32_t s_scen_tick;
static bool s_neutral_dbg;

/* ---------------- truthfulness ---------------- */

bool scene_chaton_neutral(void)
{
    if (s_neutral_dbg) { return true; }
    if (weather_mgr_forced()) { return false; }   /* debug override */
    if (!time_mgr_is_synced()) { return true; }   /* no truthful day/night */
    const weather_data_t *d = weather_mgr_data();
    if (!d || !d->valid) { return true; }
    if (weather_mgr_age_min() > 180) { return true; }
    return false;
}

void scene_chaton_set_neutral_dbg(bool on) { s_neutral_dbg = on; }

/* ---------------- scenario selection ---------------- */

const char *scene_chaton_scenario_name(void)
{
    static const char *names[SC_COUNT] = { "sleep", "loaf", "chase", "eat",
                                           "mchase", "curl" };
    return names[s_pin >= 0 ? s_pin : s_scen];
}

int scene_chaton_scenario_pin(void) { return s_pin; }

int scene_chaton_set_scenario(const char *name)
{
    if (!strcmp(name, "auto"))  { s_pin = -1; }
    else if (!strcmp(name, "sleep"))  { s_pin = SC_SLEEP; }
    else if (!strcmp(name, "loaf"))   { s_pin = SC_LOAF; }
    else if (!strcmp(name, "chase"))  { s_pin = SC_CHASE; }
    else if (!strcmp(name, "eat"))    { s_pin = SC_EAT; }
    else if (!strcmp(name, "mchase")) { s_pin = SC_MCHASE; }
    else if (!strcmp(name, "curl"))   { s_pin = SC_CURL; }
    else { return 1; }
    return 0;
}

void scene_chaton_reset(void) { s_scen_tick = 0; }

static scen_t resolve_scenario(scene_phase_t phase)
{
    if (s_pin >= 0) { return (scen_t)s_pin; }
    /* Night opens on sleep / curl under the moon; day opens on loaf. */
    static const scen_t day_order[4]   = { SC_LOAF, SC_CHASE, SC_MCHASE,
                                           SC_EAT };
    static const scen_t night_order[4] = { SC_SLEEP, SC_CURL, SC_LOAF,
                                           SC_CHASE };
    const scen_t *order = (phase == SCENE_PHASE_NIGHT) ? night_order
                                                       : day_order;
    return order[(s_scen_tick / ROT_TICKS) % 4];
}

static bool work_hours(void)
{
    if (!time_mgr_is_synced()) { return false; }
    struct tm tm;
    time_mgr_now(&tm);
    if (tm.tm_wday < 1 || tm.tm_wday > 5) { return false; }  /* Mon-Fri */
    return tm.tm_hour >= 9 && tm.tm_hour < 17;
}

/* ---------------- shared pieces ---------------- */

typedef enum { FACE_IDLE, FACE_SLEEP, FACE_LEFT, FACE_RIGHT, FACE_DOWN,
               FACE_WIDE } face_t;

static void paint_shadow(int x0, int x1, int y)
{
    scene_sfill(x0, y, x1, y, P_DARK);
}

static void paint_face(int cx, int cy, face_t face)
{
    const uint8_t *eye = art_eye_shine;
    switch (face) {
    case FACE_SLEEP: eye = art_eye_happy; break;
    case FACE_LEFT:  eye = art_eye_left;  break;
    case FACE_RIGHT: eye = art_eye_right; break;
    case FACE_DOWN:  eye = art_eye_down;  break;
    case FACE_WIDE:  eye = art_eye_wide;  break;
    case FACE_IDLE:
    default:
        if ((int)(s_tick % 40) < 2) { eye = art_eye_closed; }     /* blink */
        else if ((s_tick / 50) % 4 == 1) { eye = art_eye_left; }  /* glance */
        else if ((s_tick / 50) % 4 == 3) { eye = art_eye_right; }
        break;
    }
    scene_stamp(eye, 3, 3, cx + CAT_EYE_L_X, cy + CAT_EYE_L_Y);
    scene_stamp(eye, 3, 3, cx + CAT_EYE_R_X, cy + CAT_EYE_R_Y);
    scene_stamp(art_nose, 3, 3, cx + CAT_NOSE_X, cy + CAT_NOSE_Y);
}

/* Sitting cat with a swaying tail (period in ticks per tail step) and an
 * occasional ear twitch. */
static void paint_cat(int cx, int cy, face_t face, int sway)
{
    static const uint8_t *const tails[4] = { art_cat_sit_0, art_cat_sit_1,
                                             art_cat_sit_0, art_cat_sit_2 };
    const uint8_t *body = tails[(s_tick / (uint32_t)sway) % 4];
    if (face != FACE_SLEEP && (int)(s_tick % 70) >= 40 && (int)(s_tick % 70) < 43) {
        body = art_cat_sit_ear;                         /* ear twitch */
    }
    paint_shadow(cx + 2, cx + 34, cy + 35);
    scene_stamp(body, ART_CAT_SIT_0_W, ART_CAT_SIT_0_H, cx, cy);
    paint_face(cx, cy, face);
}

/* The umbrella goes down BEFORE the cat: its handle stands behind the head
 * and only shows between the ears. */
static void paint_umbrella(int cx, int cy)
{
    scene_stamp(art_umbrella, ART_UMBRELLA_W, ART_UMBRELLA_H,
                cx + CAT_NOSE_X + 1 - ART_UMBRELLA_W / 2, cy - 13);
}

static void paint_props(int cx, int cy, bool scarf, bool shades, bool tie)
{
    if (scarf) {
        scene_stamp(art_scarf, ART_SCARF_W, ART_SCARF_H,
                    cx + CAT_COLLAR_X - 1, cy + CAT_COLLAR_Y - 1);
    } else if (tie) {
        scene_stamp(art_bowtie, ART_BOWTIE_W, ART_BOWTIE_H,
                    cx + CAT_BELL_X - 3, cy + CAT_BELL_Y - 1);
    }
    if (shades) {
        scene_stamp(art_shades, ART_SHADES_W, ART_SHADES_H,
                    cx + CAT_EYE_L_X - 2, cy + CAT_EYE_L_Y - 1);
    }
}

static void paint_zbub(int x, int y)
{
    static const uint8_t *const frames[3] = { art_zbub_0, art_zbub_1,
                                              art_zbub_2 };
    int f = (int)((s_tick / 5) % 3);
    int rise = (int)((s_tick % 30) / 10);      /* 0..2, a slow rise */
    scene_stamp(frames[f], ART_ZBUB_0_W, ART_ZBUB_0_H, x, y - rise);
}

/* ---------------- environments ---------------- */

/* Neutral indoor scene (stale/missing data): warm wall, floor, a yellow
 * rug and a little framed pixel-M poster. No sky, no invented weather. */
static void paint_indoor(void)
{
    scene_sfill(0, 0, SCENE_W - 1, SCENE_H - 1, P_CLOUD);
    scene_sfill(0, GROUND_Y, SCENE_W - 1, SCENE_H - 1, P_BLD);
    scene_sfill(47, 65, 113, 78, P_DARK);          /* rug outline */
    scene_sfill(48, 66, 112, 77, P_BLD2);          /* rug */
    scene_sfill(117, 11, 126, 18, P_DARK);         /* poster frame */
    scene_sfill(118, 12, 125, 17, P_CLOUD);
    static const uint8_t m_map[6][7] = {
        {1,0,0,0,0,0,1},
        {1,1,0,0,0,1,1},
        {1,0,1,0,1,0,1},
        {1,0,0,1,0,0,1},
        {1,0,0,0,0,0,1},
        {1,0,0,0,0,0,1},
    };
    for (int j = 0; j < 6; j++) {
        for (int i = 0; i < 7; i++) {
            if (m_map[j][i]) { scene_sset(119 + i, 12 + j, P_ACC); }
        }
    }
}

static void paint_outdoor_ground(void)
{
    scene_sfill(0, GROUND_Y, SCENE_W - 1, SCENE_H - 1, P_BLD);
}

/* ---------------- scenarios ---------------- */

typedef struct { bool umbrella, scarf, shades, tie, startled; } dress_t;

static void sit(int cx, int cy, face_t face, int sway, const dress_t *d)
{
    if (d->umbrella) { paint_umbrella(cx, cy); }
    paint_cat(cx, cy, d->startled ? FACE_WIDE : face, sway);
    paint_props(cx, cy, d->scarf, d->shades && face != FACE_SLEEP, d->tie);
}

static void do_loaf(const dress_t *d)
{
    sit(CAT_X, CAT_Y, FACE_IDLE, 6, d);
}

static void do_sleep(const dress_t *d)
{
    sit(CAT_X, CAT_Y, FACE_SLEEP, 20, d);                 /* slow tail */
    paint_zbub(CAT_X + 25, CAT_Y - 6);
}

static void do_chase(const dress_t *d)
{
    /* A yarn ball rolls back and forth in front of the cat; the eyes
     * follow it and the tail gets excited. */
    double ph = s_tick / 18.0;
    int bx = 26 + (int)(18.0 * sin(ph));
    int by = 66;
    paint_shadow(bx, bx + 10, by + 11);
    scene_stamp(((s_tick / 4) & 1) ? art_yarn_b : art_yarn_a,
                ART_YARN_A_W, ART_YARN_A_H, bx, by);
    face_t face = (cos(ph) > 0) ? FACE_RIGHT : FACE_LEFT;
    if (bx > 36) { face = FACE_DOWN; }
    sit(CAT_X, CAT_Y, face, 3, d);
}

static void do_mchase(const dress_t *d)
{
    /* A little pixel-M block bounces along in front of the cat. */
    double ph = s_tick / 22.0;
    int bx = 24 + (int)(18.0 * sin(ph));
    int hop = (int)(8.0 * fabs(sin(s_tick / 5.0)));
    int by = 70 - hop;
    paint_shadow(bx + 1, bx + 8, 78);
    scene_stamp(art_mblock, ART_MBLOCK_W, ART_MBLOCK_H, bx, by);
    face_t face = (cos(ph) > 0) ? FACE_RIGHT : FACE_LEFT;
    sit(CAT_X, CAT_Y, face, 3, d);
}

static void do_eat(const dress_t *d)
{
    /* A croissant in front of the paws; the cat looks down at it and it
     * loses a bite every few seconds. */
    int bx = CAT_X - 16, by = CAT_Y + 29;
    paint_shadow(bx + 1, bx + 15, by + 7);
    scene_stamp(((s_tick / 30) & 1) ? art_croissant_b : art_croissant_a,
                ART_CROISSANT_A_W, ART_CROISSANT_A_H, bx, by);
    sit(CAT_X, CAT_Y, FACE_DOWN, 10, d);
}

static void do_curl(const dress_t *d)
{
    /* Lying down asleep under the moon (painted by scene.c at x=122). */
    paint_shadow(LIE_X + 2, LIE_X + 50, LIE_Y + 26);
    scene_stamp(art_cat_lie, ART_CAT_LIE_W, ART_CAT_LIE_H, LIE_X, LIE_Y);
    paint_face(LIE_X, LIE_Y, FACE_SLEEP);
    if (d->scarf) {
        scene_stamp(art_scarf, ART_SCARF_W, ART_SCARF_H,
                    LIE_X + CAT_COLLAR_X - 1, LIE_Y + CAT_COLLAR_Y - 1);
    }
    paint_zbub(LIE_X + 25, LIE_Y - 6);
}

/* ---------------- entry ---------------- */

void scene_chaton_paint(scene_phase_t phase, scene_wx_t wx, bool neutral)
{
    s_tick++;
    s_scen_tick++;
    s_scen = resolve_scenario(phase);

    if (neutral) {
        paint_indoor();
    } else {
        paint_outdoor_ground();
    }

    /* Weather/time reactions from the latest real data. In the neutral
     * indoor scene there is no truthful weather, so only the work-hours
     * tie (time-based) survives. */
    dress_t d = { 0 };
    if (!neutral) {
        d.umbrella = (wx == SCENE_WX_RAIN || wx == SCENE_WX_DRIZZLE
                      || wx == SCENE_WX_STORM);
        const weather_data_t *wd = weather_mgr_data();
        d.scarf = (wx == SCENE_WX_SNOW)
                  || (wd && wd->valid && wd->temp_c < 5.0f);
        d.shades = (phase == SCENE_PHASE_DAY && wx == SCENE_WX_CLEAR);
        d.startled = (wx == SCENE_WX_STORM && scene_bolt_active());
    }
    d.tie = work_hours() && !d.scarf;    /* the scarf covers the collar */

    switch (s_scen) {
    case SC_SLEEP:  do_sleep(&d); break;
    case SC_CHASE:  do_chase(&d); break;
    case SC_EAT:    do_eat(&d); break;
    case SC_MCHASE: do_mchase(&d); break;
    case SC_CURL:   do_curl(&d); break;
    case SC_LOAF:
    default:        do_loaf(&d); break;
    }
}
